// about.h
// 功能:游戏控制面板属性页振动页面
// 版本:1.2008.10.08
// 日期:2002/10/08
/////////////////////////////////////////////////////////////////////////////
#ifndef __ABOUT_H__
#define __ABOUT_H__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
BOOL CALLBACK	AboutProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
/////////////////////////////////////////////////////////////////////////////
#endif // __ABOUT_H__
